services:
  meetny-backend:
    build: ./backend
    container_name: meetny-backend
    env_file:
      - ./backend/.env
    expose:
      - "8081"
    networks:
      - npm-net
    restart: unless-stopped

networks:
  npm-net:
    external: true
