spring:
  config:
    import: classpath:application-secret.yml

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672   # STOMP용 포트
    username: guest
    password: guest

  logging.level:
    org.hibernate.SQL: debug