spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/joinus
    username: sa
    password:
    driver-class-name: org.h2.Driver

  rabbitmq:
    host: localhost
    port: 5672   # STOMP용 포트
    username: guest
    password: guest

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 504197790197-bl5687os7d8mkls1bf775crmcjpd3oas.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile
              - email
            client-name: Google

          naver:
            client-id: 031mIfAZhTl7r9_EjTc2
            client-secret: pRmE_wE0Z9
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            client-name: Naver

          kakao:
            client-id: 2174e1c58aa1424a07bea06e2503a878
            client-secret: ""
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - Profile_image
              - friends
              - talk_message
              - talk_calendar
              - talk_calendar_task
            client-name: Kakao

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub


          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize?prompt=login
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  mail:
    host: smtp.gmail.com
    port: 587
    username: jason20021001@gmail.com
    password: pxbk atbc azdd yusi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

jwt:
  secret: e4d431f2694e61af4408f65107f8dcbe96e5a6948036ca315cebcf4cac04cf15