spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/joinus
    username: sa
    password:
    driver-class-name: org.h2.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: jason20021001@gmail.com
    password: pxbk atbc azdd yusi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

jwt:
  secret: e4d431f2694e61af4408f65107f8dcbe96e5a6948036ca315cebcf4cac04cf15