spring:
  datasource:
    url: jdbc:mysql://localhost:3306/JoinUs
    username: root
    password: ansxoddl123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  # src/main/resources/application.yml
  jwt:
    secret: 119b89085ac0c1cf8b98c3704a46add5de7b7c36204c98087513147d8615e602

  logging.level:
    org.hibernate.SQL: debug