package mjc.capstone.joinus.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
public enum ErrorCode {
    MEMBER_NOT_FOUND(HttpStatus.NOT_FOUND, "MEMBER_NOT_FOUND"),
    POST_NOT_FOUND(HttpStatus.NOT_FOUND, "POST_NOT_FOUND"),
    REVIEW_NOT_FOUND(HttpStatus.NOT_FOUND, "REVIEW_NOT_FOUND"),
    REVIEW_TAGET_NOT_FOUND(HttpStatus.NOT_FOUND, "REVIEW_TAG_NOT_FOUND"),
    INVALID_INPUT(HttpStatus.BAD_REQUEST, "INVALID_INPUT"),
    INVALID_TOKEN(HttpStatus.UNAUTHORIZED, "INVALID_TOKEN"),
    MISSING_REVIEW_TAG(HttpStatus.BAD_REQUEST, "MISSING_REVIEW_TAG"),
    EMAIL_NOT_VERIFIED(HttpStatus.FORBIDDEN, "EMAIL_NOT_VERIFIED"),
    DUPLICATE_REVIEW(HttpStatus.CONFLICT, "DUPLICATE_REVIEW"),
    DUPLICATE_REVIEW_TAG(HttpStatus.CONFLICT, "DUPLICATE_REVIEW_TAG"),
    DUPLICATE_EMAIL(HttpStatus.CONFLICT, "DUPLICATE_EMAIL"),
    DUPLICATE_NICKNAME(HttpStatus.CONFLICT, "DUPLICATE_NICKNAME"),
    IMAGE_SAVE_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "Internal Server Error"),
    INVALID_IMAGE(HttpStatus.UNSUPPORTED_MEDIA_TYPE, "INVALID_IMAGE"),
    NOT_MEMBER_FOUND(HttpStatus.NOT_FOUND, "NOT_MEMBER_FOUND"),
    NOT_FOUND_POST(HttpStatus.NOT_FOUND, "NOT_FOUND_POST"),
    NOT_FOUND_MEMBER(HttpStatus.NOT_FOUND, "NOT_FOUND_MEMBER"),
    NOT_FOUND_CHATROOM(HttpStatus.NOT_FOUND, "NOT_FOUND_CHATROOM"),
    DUPLICATE_PARTICIPANT(HttpStatus.CONFLICT, "DUPLICATE_PARTICIPANT"),
    REVIEW_ACCESS_DENIED(HttpStatus.UNAUTHORIZED, "REVIEW_ACCESS_DENIED"),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "INTERNAL_ERROR");

    private final HttpStatus status;
    private final String message;

    ErrorCode(HttpStatus staus, String internalError) {
        this.status = staus;
        this.message = internalError;
    }
}